import { useEffect, useState } from "react";
import { useFormik } from "formik";
import { toast } from "react-toastify";
import { GoBackButton, OverlayLoading, SubmitButton } from "../../components";
import { get, post } from "../../utills";
import { API_URL } from "../../constants";
import { addUrlToFile } from "../../utills/addUrlToFile";
import { emptyItem, emptySection, SustainabilityGroup, SustainabilityItem, SustainabilityPageValues, SustainabilitySection, sustainabilityPageInitialValues, sustainabilityPageSchema } from "../../validationSchemas/sustainabilityPageSchema";

const endpoint = "/sustainabilityPage";
const item = (value?: Partial<SustainabilityItem>): SustainabilityItem => ({ label: value?.label || "", description: value?.description || "" });
const removeAt = <T,>(values: T[], index: number) => values.filter((_, current) => current !== index);
const normalize = (data: Partial<SustainabilityPageValues>): SustainabilityPageValues => ({ ...sustainabilityPageInitialValues, ...data, breadcrumb: { ...sustainabilityPageInitialValues.breadcrumb, ...(data.breadcrumb || {}) }, intro: { ...sustainabilityPageInitialValues.intro, ...(data.intro || {}), paragraphs: data.intro?.paragraphs || [] }, sections: (data.sections || []).map((section) => ({ ...emptySection(), ...section, paragraphs: section.paragraphs || [], items: (section.items || []).map(item), groups: (section.groups || []).map((group) => ({ title: group.title || "", items: (group.items || []).map(item) })), images: section.images || [] })), seo: { ...sustainabilityPageInitialValues.seo, ...(data.seo || {}), keywords: data.seo?.keywords || [] } });

function TextInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="mb-3"><label className="form-label">{label}</label><input className="form-control" value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function ItemEditor({ value, onChange, onRemove }: { value: SustainabilityItem; onChange: (value: SustainabilityItem) => void; onRemove: () => void }) { return <div className="row border rounded p-2 mb-2"><div className="col-md-4"><TextInput label="Label" value={value.label} onChange={(label) => onChange({ ...value, label })} /></div><div className="col-md-7"><TextInput label="Description" value={value.description} onChange={(description) => onChange({ ...value, description })} /></div><div className="col-md-1 pt-4"><button type="button" className="btn btn-outline-danger" onClick={onRemove}>X</button></div></div>; }

export function SustainabilityPageContent() {
  const [loading, setLoading] = useState(true); const [updating, setUpdating] = useState(false);
  const formik = useFormik<SustainabilityPageValues>({ initialValues: sustainabilityPageInitialValues, validationSchema: sustainabilityPageSchema, onSubmit: async (values) => { setUpdating(true); const payload = { name: values.name, breadcrumb: values.breadcrumb, intro: values.intro, sections: values.sections, seo: values.seo }; const response = await post(endpoint, payload, true); if (response?.status === 200) { toast.success(response.message); formik.setValues(normalize(response.body)); } else toast.error(response?.message || "Unable to save"); setUpdating(false); } });
  useEffect(() => { get(endpoint, true).then((response) => { if (response?.status === 200) formik.setValues(normalize(response.body)); else toast.error(response?.message); setLoading(false); }); }, []);
  const setSection = (index: number, section: SustainabilitySection) => formik.setFieldValue(`sections[${index}]`, section);
  const addParagraph = (index?: number) => index === undefined ? formik.setFieldValue("intro.paragraphs", [...formik.values.intro.paragraphs, ""]) : setSection(index, { ...formik.values.sections[index], paragraphs: [...formik.values.sections[index].paragraphs, ""] });
  const updateGroup = (sectionIndex: number, groupIndex: number, group: SustainabilityGroup) => setSection(sectionIndex, { ...formik.values.sections[sectionIndex], groups: formik.values.sections[sectionIndex].groups.map((value, index) => index === groupIndex ? group : value) });
  const uploadBanner = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { toast.error("Please select a JPG, PNG or WEBP image"); return; }
    const formData = new FormData(); formData.append("files", file);
    try {
      const response = await fetch(`${API_URL}/media`, { method: "POST", body: formData, headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });
      const data = await response.json();
      if (data.status === 200 && data.body?.[0]?.filename) { formik.setFieldValue("breadcrumb.bannerImage", data.body[0].filename); toast.success("Banner uploaded"); } else toast.error(data.message || "Banner upload failed");
    } catch (error: any) { toast.error(error?.message || "Banner upload failed"); }
    event.target.value = "";
  };
  const uploadSectionImage = async (sectionIndex: number, imageIndex: number, event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) { toast.error("Please select a JPG, PNG or WEBP image"); return; }
    const formData = new FormData(); formData.append("files", file);
    try {
      const response = await fetch(`${API_URL}/media`, { method: "POST", body: formData, headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });
      const data = await response.json();
      if (data.status === 200 && data.body?.[0]?.filename) { setSection(sectionIndex, { ...formik.values.sections[sectionIndex], images: formik.values.sections[sectionIndex].images.map((image, currentIndex) => currentIndex === imageIndex ? { ...image, image: data.body[0].filename } : image) }); toast.success("Image uploaded"); } else toast.error(data.message || "Image upload failed");
    } catch (error: any) { toast.error(error?.message || "Image upload failed"); }
    event.target.value = "";
  };

  return <div className="content-wrapper"><div className="row"><div className="col-md-12 grid-margin"><div className="d-flex gap-2 align-items-center"><GoBackButton /><h4 className="font-weight-bold mb-0">Sustainability Page Content</h4></div></div></div>{loading && <OverlayLoading />}<form onSubmit={formik.handleSubmit}>
    <div className="card mb-4"><div className="card-body"><h5>Page Settings</h5><TextInput label="Page Name" value={formik.values.name} onChange={(value) => formik.setFieldValue("name", value)} /><TextInput label="Breadcrumb Title" value={formik.values.breadcrumb.title} onChange={(value) => formik.setFieldValue("breadcrumb.title", value)} /><div className="mb-3"><label className="form-label">Banner Image (optional)</label><input type="file" className="form-control" accept="image/jpeg,image/png,image/webp" onChange={uploadBanner} />{formik.values.breadcrumb.bannerImage && <div className="mt-3 d-flex align-items-center gap-3"><img src={addUrlToFile(formik.values.breadcrumb.bannerImage)} alt="Banner preview" style={{ height: 90, width: 180, objectFit: "cover" }} /><button type="button" className="btn btn-outline-danger" onClick={() => formik.setFieldValue("breadcrumb.bannerImage", "")}>Remove</button></div>}</div></div></div>
    <div className="card mb-4"><div className="card-body"><h5>Introduction</h5><TextInput label="Heading" value={formik.values.intro.title} onChange={(value) => formik.setFieldValue("intro.title", value)} />{formik.values.intro.paragraphs.map((value, index) => <div className="input-group mb-2" key={index}><textarea className="form-control" rows={3} value={value} onChange={(event) => formik.setFieldValue(`intro.paragraphs[${index}]`, event.target.value)} /><button type="button" className="btn btn-outline-danger" onClick={() => formik.setFieldValue("intro.paragraphs", removeAt(formik.values.intro.paragraphs, index))}>X</button></div>)}<button type="button" className="btn btn-outline-primary" onClick={() => addParagraph()}>+ Add Paragraph</button></div></div>
    {formik.values.sections.map((section, sectionIndex) => <div className="card mb-4" key={sectionIndex}><div className="card-body"><div className="d-flex justify-content-between"><h5>Section {sectionIndex + 1}</h5><button type="button" className="btn btn-outline-danger" onClick={() => formik.setFieldValue("sections", removeAt(formik.values.sections, sectionIndex))}>Remove Section</button></div><div className="row"><div className="col-md-4"><TextInput label="Section ID" value={section.id} onChange={(id) => setSection(sectionIndex, { ...section, id })} /></div><div className="col-md-8"><TextInput label="Title" value={section.title} onChange={(title) => setSection(sectionIndex, { ...section, title })} /></div></div><TextInput label="Subtitle (optional)" value={section.subtitle} onChange={(subtitle) => setSection(sectionIndex, { ...section, subtitle })} />
      <h6>Paragraphs</h6>{section.paragraphs.map((value, index) => <div className="input-group mb-2" key={index}><textarea className="form-control" rows={3} value={value} onChange={(event) => setSection(sectionIndex, { ...section, paragraphs: section.paragraphs.map((current, currentIndex) => currentIndex === index ? event.target.value : current) })} /><button type="button" className="btn btn-outline-danger" onClick={() => setSection(sectionIndex, { ...section, paragraphs: removeAt(section.paragraphs, index) })}>X</button></div>)}<button type="button" className="btn btn-sm btn-outline-primary mb-3" onClick={() => addParagraph(sectionIndex)}>+ Add Paragraph</button>
      <TextInput label="Items Group Title (optional)" value={section.itemsTitle} onChange={(itemsTitle) => setSection(sectionIndex, { ...section, itemsTitle })} /><h6>{section.itemsTitle || "Items"}</h6>{section.items.map((value, index) => <ItemEditor key={index} value={value} onChange={(next) => setSection(sectionIndex, { ...section, items: section.items.map((current, currentIndex) => currentIndex === index ? next : current) })} onRemove={() => setSection(sectionIndex, { ...section, items: removeAt(section.items, index) })} />)}<button type="button" className="btn btn-sm btn-outline-primary mb-3" onClick={() => setSection(sectionIndex, { ...section, items: [...section.items, emptyItem()] })}>+ Add Item</button>
      <h6>Groups</h6>{section.groups.map((group, groupIndex) => <div className="border rounded p-3 mb-3" key={groupIndex}><TextInput label="Group Title" value={group.title} onChange={(title) => updateGroup(sectionIndex, groupIndex, { ...group, title })} />{group.items.map((value, itemIndex) => <ItemEditor key={itemIndex} value={value} onChange={(next) => updateGroup(sectionIndex, groupIndex, { ...group, items: group.items.map((current, currentIndex) => currentIndex === itemIndex ? next : current) })} onRemove={() => updateGroup(sectionIndex, groupIndex, { ...group, items: removeAt(group.items, itemIndex) })} />)}<button type="button" className="btn btn-sm btn-outline-primary" onClick={() => updateGroup(sectionIndex, groupIndex, { ...group, items: [...group.items, emptyItem()] })}>+ Add Group Item</button><button type="button" className="btn btn-sm btn-outline-danger ms-2" onClick={() => setSection(sectionIndex, { ...section, groups: removeAt(section.groups, groupIndex) })}>Remove Group</button></div>)}<button type="button" className="btn btn-sm btn-outline-primary" onClick={() => setSection(sectionIndex, { ...section, groups: [...section.groups, { title: "", items: [] }] })}>+ Add Group</button>
      <h6 className="mt-3">Additional Paragraphs / Notes</h6>{section.footerParagraphs.map((value, index) => <div className="input-group mb-2" key={index}><textarea className="form-control" rows={2} value={value} onChange={(event) => setSection(sectionIndex, { ...section, footerParagraphs: section.footerParagraphs.map((current, currentIndex) => currentIndex === index ? event.target.value : current) })} /><button type="button" className="btn btn-outline-danger" onClick={() => setSection(sectionIndex, { ...section, footerParagraphs: removeAt(section.footerParagraphs, index) })}>X</button></div>)}<button type="button" className="btn btn-sm btn-outline-primary mb-3" onClick={() => setSection(sectionIndex, { ...section, footerParagraphs: [...section.footerParagraphs, ""] })}>+ Add Paragraph</button>
      <h6>Optional Images</h6>{section.images.map((image, imageIndex) => <div className="border rounded p-3 mb-2" key={imageIndex}><div className="row"><div className="col-md-4"><label className="form-label">Upload Image</label><input type="file" className="form-control" accept="image/jpeg,image/png,image/webp" onChange={(event) => uploadSectionImage(sectionIndex, imageIndex, event)} />{image.image && <div className="mt-2 d-flex align-items-center gap-2"><img src={addUrlToFile(image.image)} alt={image.alt || "Section preview"} style={{ height: 70, width: 120, objectFit: "cover" }} /><small className="text-muted">{image.image}</small></div>}</div><div className="col-md-3"><TextInput label="Alt Text" value={image.alt} onChange={(value) => setSection(sectionIndex, { ...section, images: section.images.map((current, currentIndex) => currentIndex === imageIndex ? { ...current, alt: value } : current) })} /></div><div className="col-md-4"><TextInput label="Caption" value={image.caption} onChange={(value) => setSection(sectionIndex, { ...section, images: section.images.map((current, currentIndex) => currentIndex === imageIndex ? { ...current, caption: value } : current) })} /></div><div className="col-md-1 pt-4"><button type="button" className="btn btn-outline-danger" onClick={() => setSection(sectionIndex, { ...section, images: removeAt(section.images, imageIndex) })}>X</button></div></div></div>)}<button type="button" className="btn btn-sm btn-outline-primary" onClick={() => setSection(sectionIndex, { ...section, images: [...section.images, { image: "", alt: "", caption: "" }] })}>+ Add Image</button>
    </div></div>)}<button type="button" className="btn btn-primary mb-4" onClick={() => formik.setFieldValue("sections", [...formik.values.sections, emptySection()])}>+ Add Section</button>
    <div className="card mb-4"><div className="card-body"><h5>SEO</h5><TextInput label="Meta Title" value={formik.values.seo.metaTitle} onChange={(value) => formik.setFieldValue("seo.metaTitle", value)} /><TextInput label="Meta Description" value={formik.values.seo.metaDescription} onChange={(value) => formik.setFieldValue("seo.metaDescription", value)} /><TextInput label="Keywords (comma separated)" value={formik.values.seo.keywords.join(", ")} onChange={(value) => formik.setFieldValue("seo.keywords", value.split(",").map((item) => item.trim()).filter(Boolean))} /></div></div><div className="d-flex justify-content-end mt-4 mb-5"><SubmitButton loading={updating} text="Save Sustainability Page" /></div>
  </form></div>;
}
