export const createProduct = {
  headers: [
    { label: "NAME*", key: "name" },
    { label: "SLUG", key: "slug" },
    { label: "CATEGORY*", key: "category" },
    { label: "SUB CATEGORY*", key: "subCategory" },

    { label: "SKU", key: "sku" },
    { label: "IMAGE*", key: "image" },
    { label: "FEATURES*", key: "features" },
    { label: "DESCRIPTIONS", key: "descriptions" },
    { label: "SHORT DESCRIPTIONS", key: "shortDescriptions" },
    { label: "BENEFITS", key: "benefits" },
    { label: "SPECIFICATIONS", key: "specifications" },

    { label: "VARIANT SKU*", key: "v_sku" },
    { label: "VARIANT COLOR*", key: "v_color" },
    { label: "VARIANT SHAPE*", key: "v_shape" },
    { label: "VARIANT MATERIAL*", key: "v_material" },
    { label: "VARIANT SIZE*", key: "v_size" },
    { label: "VARIANT THICKNESS*", key: "v_thickness" },
    { label: "VARIANT IMAGES*", key: "v_images" },
    { label: "VARIANT BADGES*", key: "v_badges" },
    { label: "VARIANT DESCRIPTIONS*", key: "v_descriptions" },
    { label: "VARIANT STATUS*", key: "v_status" },

    { label: "META TITLE", key: "metaTitle" },
    { label: "META DESCRIPTION", key: "metaDescription" },
    { label: "META KEYWORDS", key: "metaKeywords" },
    { label: "STATUS*", key: "status" },
  ],
  data: [
    {
      name: "Product One",
      slug: "product-one",
      category: "category-one",
      subCategory: "subcat-one,subcat-two",

      sku: "",
      image: "1SlazcstYGKiEPwV5ReQeah_8OqqApgSr",
      features: "f1,f2,f3",
      descriptions: "Long Descriptions",
      shortDescriptions: "Short Description",
      benefits: "Write Benifits",
      specifications: "Write Specifications",

      v_sku: "",
      v_color: "",
      v_shape: "",
      v_material: "",
      v_size: "",
      v_thickness: "",
      v_images: "",
      v_badges: "",
      v_descriptions: "",
      v_status: "",

      metaTitle: "",
      metaDescription: "",
      metaKeywords: "",
      status: "TRUE",
    },
  ],
};

export const updateProduct = {
  headers: [
    { label: "id", key: "id" },
    { label: "name", key: "name" },
    { label: "slug", key: "slug" },
    { label: "categories", key: "categories" },
    { label: "subCategories", key: "subCategories" },
    { label: "decorSeries", key: "decorSeries" },
    { label: "decorName", key: "decorName" },
    { label: "decorNumber", key: "decorNumber" },
    { label: "ralNumber", key: "ralNumber" },
    { label: "subCategories", key: "subCategories" },
    { label: "sku", key: "sku" },
    { label: "sizes", key: "sizes" },
    { label: "a4Image", key: "a4Image" },
    { label: "fullSheetImage", key: "fullSheetImage" },
    { label: "highResolutionImage", key: "highResolutionImage" },
    { label: "metaTitle", key: "metaTitle" },
    { label: "metaDescription", key: "metaDescription" },
    { label: "metaKeywords", key: "metaKeywords" },
    { label: "status", key: "status" },
  ],
};
